### ISSUE TITLE
Tydom 2

### ISSUE THREAD

**Issue by JNoVernay** [CyrilP/hass-deltadore-tydom-component#53]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Bonjour, Merci tout d'abord pour ce développement ! 
ce n'est probablement pas un problème dû au module, mais je me demande si l'intégration d'une alarme Tyxal+ au travers de Tydom 2 est possible : lorsque j'ai intégré Tydom 2, je sors avec 3 tableaux. 1 sur la mise à jour, 1 sur les capteurs et 1 sur les diagnostics. Sur ces 3 tableaux, rien à dire, tout semble correct. Mais le principal que je recherche est de pouvoir gérer l'alarme elle-même avec un tableau de "gestion de l'alarme".

[Capture d’écran 2024-02-14 à 08.32.36.pdf](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14276592/Capture.d.ecran.2024-02-14.a.08.32.36.pdf)

### Describe the solution you'd like

Disposer, si cela est possible, du panneau de gestion de l'alarme.
Merci, 
Jean-Noël

### Describe alternatives you've considered

Aucune

### Additional context

Non

**Comment by CyrilP** [comment]
Bonjour, 
le problème c'est que je n'ai pas d'alarme pour pouvoir tester.
Je peux essayer de faire quelque chose quand même, j'ai une partie du code qu'il faut. 
Je veux bien les traces des réponses du tydom au démarrage. 
Pouvez-vous mettre l'intégration en debug, relancer HomeAssistant et m'envoyer les logs sans la première partie qui concernent l'authentification svp ? je vais essayer de trouver un peu de temps pour regarder

**Comment by JNoVernay** [comment]
Bonjour et merci,
Entre temps j'avais basculé vers une tentative (encore infructueuse) via tydom2mqtt.
Je ne sais pas si c'est cela que vous cherchez mais j'ai le journal suivant :
19 février 2024 
a été éteint 
07:20:32 - Il y a 5 minutes 
a été éteint 
07:20:32 - Il y a 5 minutes 
a été allumé 
07:20:32 - Il y a 5 minutes 
a changé en mediation.tydom.com 
07:20:32 - Il y a 5 minutes 
a changé en 01.00.03 
07:20:32 - Il y a 5 minutes 
a changé en P21260012 
07:20:32 - Il y a 5 minutes 
a changé en 2.0.4-00.01 
07:20:32 - Il y a 5 minutes 
a changé en 21260011 
07:20:32 - Il y a 5 minutes 
a changé en 04.00.50 
07:20:32 - Il y a 5 minutes 
a changé en 00.00.01 
07:20:32 - Il y a 5 minutes 
a changé en 01.04.14 
07:20:32 - Il y a 5 minutes 
a changé en 21260010 
07:20:32 - Il y a 5 minutes 
a changé en 6414118 
07:20:32 - Il y a 5 minutes 
a changé en 00.00.01 
07:20:32 - Il y a 5 minutes 
a changé en 03.15.33 
07:20:32 - Il y a 5 minutes 
a été allumé 
07:20:32 - Il y a 5 minutes 
a changé en 0 
07:20:32 - Il y a 5 minutes 
a été éteint 
07:20:32 - Il y a 5 minutes 
a changé en prod 
07:20:32 - Il y a 5 minutes 
a changé en 001********** 
07:20:32 - Il y a 5 minutes 
a changé en TYDOM2 
07:20:32 - Il y a 5 minutes 
a été éteint 
07:20:32 - Il y a 5 minutes

**Comment by CyrilP** [comment]
Pour activer le debug, il faut suivre ce qui est marqué là :
https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
Il faut activer le debug, redémarrer Home Assistant et désactiver le debug. à ce moment là, Il sauvegarde les traces.
On peut aussi les retrouver dans homeassistant.log

**Comment by JNoVernay** [comment]
Bonjour, désolé pour le délai de réponse.
[home-assistant_mqtt_2024-02-23T06-16-28.991Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14382242/home-assistant_mqtt_2024-02-23T06-16-28.991Z.log)

**Comment by CyrilP** [comment]
Bonjour, 
ce sont les logs de MQTT, je préfèrerais avoir les logs de ce module. 
j'ai implémenté un mode qui permet de les utiliser pour simuler une connexion au Tydom à partir des logs. 
Ca me permettra de tester en partie des équipements que je n'ai pas

**Comment by JNoVernay** [comment]
Bonjour,
Il y a beaucoup d'informations dans le fichier et je ne sais pas juger de la criticité de certaines. Peut-on échanger ce fichier par un canal plus privé ?
Par ailleurs, l'activation du module conduit à un mode d'interrogation permanent du système Tydom (la box clignote en continu) que je n'ai pas avec mes applis actuelles (Delta Dore, Lifedomus...), cela me pose question...

Jean-Noël

________________________________
De : CyrilP ***@***.***>
Envoyé : vendredi 1 mars 2024 19h36
À : CyrilP/hass-deltadore-tydom-component ***@***.***>
Cc : JNoVernay ***@***.***>; Author ***@***.***>
Objet : Re: [CyrilP/hass-deltadore-tydom-component] Tydom 2 (Issue #53)


Bonjour,
ce sont les logs de MQTT, je préfèrerais avoir les logs de ce module.
j'ai implémenté un mode qui permet de les utiliser pour simuler une connexion au Tydom à partir des logs.
Ca me permettra de tester en partie des équipements que je n'ai pas

**Comment by CyrilP** [comment]
Bonjour, 
vous pouvez mon contacter à cette adresse cyrilp-sec@protonmail.com

**Comment by timonte53** [comment]
Bonjour @JNoVernay ,
Je suis moi aussi avec une tydom 2, je n’arrive malheureusement pas la connecter, l’intégration détecte bien ma tydom et lorsque je rentre toutes les informations pour ajouter l'entité cela ne fonctionne pas malgré le fait que la box clignote en vert et que j’appuie bien sur le bouton.
Pouvez vous me dire de quelle manière avez vous ajouter la tydom 2 à l’intégration si vous repassez par ici :) ?

**Comment by JNoVernay** [comment]
Bonjour, juste par l’intégration sans astuce particulière… l’intégration remonte 2 entités, celle de Tydom 2 (Tydom-xxxx) et celle de l’alarme « Tyxal alarme » qui permet d’activer et désactiver l’alarme. Un widget sort de l’intégration et j’utilise également la carte panneau d’alarme avec l’entité « Tyxal alarme ». 
Jean-Noël

**Comment by timonte53** [comment]
Merci, je dois donc avoir un soucis quelque part dans ma configuration :)

Bonne journée,
