### ISSUE TITLE
Contrôles des lumières avec box Tydom 1.0

### ISSUE THREAD

**Issue by Thanouz** [CyrilP/hass-deltadore-tydom-component#55]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Bonjour et merci pour cette intégration. La doc dit que cette intégration doit créer entre autres la platform _light_ afin de pouvoir contrôler des lampes, mais je n'ai que les sensors qui me remontent leurs états, impossible de les contrôler. Pour les volets roulantes en revanche tout est ok j'ai leur état et je peux les contrôler.

### Describe the solution you'd like

Pouvoir contrôler les lumières (aussi bien on/off que les led avec variateurs 0-100%) depuis l'intégration tydom HA.

### Describe alternatives you've considered

Pas d'alternative particulière.

### Additional context

RAS

**Comment by CyrilP** [comment]
Bonjour, comme je n'ai pas ce qu'il faut pour tester chez moi, je n'ai pas implémenté complètement le contrôle des éclairages.
Il ne manque pas grand chose.
Je veux bien les traces en débug de l'integration en debug : 
- mettre l'intégration en debug :  https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
- redémarrer home assistant pour avoir les traces d'init
- désactiver le debug et récupérer le fichier de traces.
je pense qu'avec tout ce qu'il y a dans les message de metadata et de data je pourrai m'en sortir

**Comment by Thanouz** [comment]
Voici le log : 
[home-assistant_deltadore_tydom_2024-02-26T20-52-47.188Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14411156/home-assistant_deltadore_tydom_2024-02-26T20-52-47.188Z.log)

**Comment by CyrilP** [comment]
Je viens de publier une version beta v0.5-dev
Pouvez-vous tester et me dire si ça fonctionne correctement ?
Si vous utilisez hacs, il faut actualiser les informations, faire télécharger et cocher "afficher les versions beta"

**Comment by CyrilP** [comment]
je viens de rajouter une modification sur la même version pour essayer de prendre en compte la porte du garage. Pouvez-vous tester ça aussi et me faire un retour ?

**Comment by Thanouz** [comment]
Hello, a priori ça fonctionne :) je n'ai pas testé toutes les lampes mais quelques unes avec variateur et d'autres sans, ainsi que le portail du garage, c'est ok ! Merci beaucoup.

**Comment by CyrilP** [comment]
Super ! 
je vais merger ça dans les prochains jours et faire une release officielle.
Pouvez-vous me donner les références des modules Delta Dore afin que je puisse les ajouter à la liste des équipements testés ?

**Comment by Thanouz** [comment]
Hello, je ne sais pas si c'est lié, je viens d'avoir ceci : 
![image](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/38312490/0db2182e-58a5-46f0-bc00-3134c0de515a)

Pour les modules je ne me souviens plus desquels il s'agit, depuis l'app Tydom je ne peux pas les voir.

**Comment by diadeluz** [comment]
Bonjour,

Merci++ pour cette intégration.

Je confirme le bon fonctionnement de cette version avec le module suivant:
- Récepteur pilotage radio lampe appoint TYXIA 6610

**Comment by CyrilP** [comment]
> Bonjour, [Message édité avec précisions]
> 
> Merci++ pour cette intégration.
> 
> Je confirme le fonctionnement de cette version avec le module TYXIA 6610 (switch remplaçant un interrupteur de type "poire" sur l'arrivée du 220V sur une lampe et permettant le contrôle on/off de la lampe par le bouton ou à partir de la Tydom 1.0)
> 
> Un device light est bien créé par l'installation de l'intégration et les les méthodes turn_on et turn_off permettent bien allumage et extinction physique de la lampe.
> 
> MAIS lorsque je lance l'allumage via le toggler graphique sur la page du device, celio-ci repasse à off après quelques secondes (physiquement la lampe reste allumée). Même chose à l'extinction : pour obtenir celle-ci il faut toggler 2 fois : vers on puis vers off.
> 
> D'autre part, une automation avec trigger turn_on ou turn_off de ce device n'est jamais déclenchée et le log du device ne reflète pas ses changements d'état.
> 
> Je vous joins le log lors du dernier allumage. N'hésitez pas )à me demander d'autres logs.
> 
> `` 2024-03-10 03:33:42.351 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /info) 2024-03-10 03:33:43.577 DEBUG (MainThread) [custom_components.deltadore_tydom] response status : 401 headers : <CIMultiDictProxy('Connection': 'close', 'WWW-Authenticate': 'Digest realm="Protected Area", qop="auth", nonce="2241ceec1d6a28b586cf15d4257dfd8e", opaque="6f70dbe3d82e96e2db2402bcc1d31661"', 'Content-Type': 'text/html')> content : <!doctype html>
> <title>Error 401</title>
> ## Error 401
> 
> Authorization required
> 
> 2024-03-10 03:33:43.578 INFO (MainThread) [custom_components.deltadore_tydom] nonce : 2241ceec1d6a28b586cf15d4257dfd8e 2024-03-10 03:33:44.768 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (PUT /configs/gateway/api_mode) 2024-03-10 03:33:44.768 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /groups/file) 2024-03-10 03:33:44.769 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (POST /refresh/all) 2024-03-10 03:33:44.770 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /configs/file) 2024-03-10 03:33:44.770 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/meta) 2024-03-10 03:33:44.771 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/cmeta) 2024-03-10 03:33:44.771 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/data) 2024-03-10 03:33:44.771 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /scenarios/file)

Je vais regarder. Votre log n'est pas complet par contre. Il faudrait qu'il soit en debug et avoir la trace du changement d'état de la lampe et un peu de temps après pour voir si une donnée remonte pour savoir s'il y a un problème de traitement ou s'il faut rafraichir la valeur.

**Comment by diadeluz** [comment]
Bonsoir,
Merci pour votre réponse.
Voici un log plus complet.
[home-assistant_deltadore_tydom_2024-03-12T22-19-53.692Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14579344/home-assistant_deltadore_tydom_2024-03-12T22-19-53.692Z.log)

**Comment by CyrilP** [comment]
merci pour le log. 
Au moment où vous avez actionné la lampe, il semble qu'il manque les logs de réponse. c'est peut-être dû à une erreur que je constate dans les logs qui concerne le chauffage. Il semble qu'il ne reconnaisse pas la constante TURN_OFF. quelle version d'Home Assistant avez vous ?

**Comment by CyrilP** [comment]
@Thanouz j'ai remarqué dans vos trace la présence d'un appareil appelé "Produit 1" qui n'a pas de type. 
A quoi ça correspond ? est ce que je dois essayer de le gérer aussi ?

**Comment by Thanouz** [comment]
@CyrilP Alors aucune idée, je ne le retrouve pas dans les entités/appareils de l'intégration Delta Dore TYDOM ... donc j'ai envie de vous dire "ne vous en préoccupez pas" ... si je le retrouve je vous en ferai part mais là impossible de le retrouver dans HA.

**Comment by diadeluz** [comment]
@CyrilP HA core est en 2023.11.2. Je vais upgrader vers la dernière version et vous tient au courant. 

Pour info l’app Tydom voit un module chauffage Calybox mais l'intégration ne semble  pas avoir créé de device correspondant dans HA. Pas grave pour moi car je prévois de mettre la gestion du chauffage sous HA via l’intégration Cozytouch.

**Comment by CyrilP** [comment]
@diadeluz effectivement, le statut n'a pas l'air de remonter automatiquement. 
je vais tenter de mettre un rafraichissement. si seulement je pouvais savoir dans quel cas le mettre, ce serait plus simple mais je vais improviser.
je vais tenter aussi de corriger la suite du problème avec la Calybox pour ne plus que ça plante. En fait elle remonte beaucoup moins d'informations que mon Typass.

**Comment by CyrilP** [comment]
@diadeluz je publie une nouvelle pré-release v0.6-dev2 qui devrait corriger le plantage de la Calybox et un pb avec les alarmes. je verrai la semaine prochaine pour le rafraichissement

**Comment by diadeluz** [comment]
@CyrilP  merci pour ces nouvelles . 

Cependant je ne parviens plus à installer les pre-releases (erreur "failed to load integration" si j'ai écrasé le folder /detadore_tydom lors de l'unzip des pre-releases ou le choix Delta Dore Tydom n'est pas présent dans la combo box add integration si j'ai préalablement supprimé l'intégration depuis l'interface, effacé le folder correspondant, redémarré HA et unzippé la pré-release) => je suis repassé en 0.5 et j'attends vos conseils: visiblement il y a qqch que je ne comprends pas :(

Par ailleurs concernant le Tyxia  6610 est-ce que l'intégrer sous forme de switch ne résoudrait pas mon problème ?

Bon weekend.

**Comment by CyrilP** [comment]
le tyxia 6610 sous forme de switch aura le même problème tant que son état n'est pas remonté par la gateway tydom

**Comment by diadeluz** [comment]
@CyrilP  Le Tyxia et la Calybox sont bien vus par HA vec la dev5 et l'état du Tyxia remonte correctement.
Impeccable donc.
Mille mercis.

**Comment by CyrilP** [comment]
Super. Je vais faire une release stable prochainement !

**Comment by diadeluz** [comment]
Pour info, l’UI donne des messages d’erreur dans le cas de scènes qui incluent le Tyxia :
- Failed to call service scene/turn_on. unhashable type: ‘NodeListClass’ à l’activation depuis l’UI d’une scène devant allumer la Tyxia et qui ne le fait PAS.
- Failed to call service scene/apply. unhashable type: ‘list’ à la sortie depuis l’UI d’une scène venant d’éteindre effectivement la Tyxia.

**Comment by CyrilP** [comment]
j'ai créé une scène avec le Tyxia, je ne constate pas le problème.
