### ISSUE TITLE
Tyxal alarm CSX40

### ISSUE THREAD

**Issue by Misxs** [CyrilP/hass-deltadore-tydom-component#58]
### System Health details

CSX alarm is not working and not show in the log. Log report feature not availalbe 

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have a CSX40 alarm system and it is not report by this addon. I get an error message : 
Logger: custom_components.deltadore_tydom
Source: custom_components/deltadore_tydom/hub.py:237
Integration: Delta Dore TYDOM ([documentation](https://github.com/CyrilP/hass-deltadore-tydom-component), [issues](https://github.com/CyrilP/hass-deltadore-tydom-component/issues))
First occurred: 1 mars 2024 à 14:33:39 (2 occurrences)
Last logged: 12:21:40

Alarm Not implemented yet.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Logger: custom_components.deltadore_tydom
Source: custom_components/deltadore_tydom/hub.py:237
Integration: Delta Dore TYDOM (documentation, issues)
First occurred: 1 mars 2024 à 14:33:39 (2 occurrences)
Last logged: 12:21:40

Alarm Not implemented yet.
```

**Comment by CyrilP** [comment]
Can you please provide integration logs in debug :

- activate integration debug mode : https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
- restart home assistant so than initialization messages are logged
- disable debug mode and download the log files.
- remove login informations from the messages such as email, passwords. you can also hide the macaddress but please just replace it with other characters as the size of the messages is important to replay them with my tools

I'll try my best to implement something from that logs with your help as I don't have an alarm.

**Comment by Misxs** [comment]
thanks a lot for your help. here is the log file.

[home-assistant_deltadore_tydom_2024-03-05T23-56-19.833Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14502957/home-assistant_deltadore_tydom_2024-03-05T23-56-19.833Z.log)
hope it will help.

**Comment by CyrilP** [comment]
Thanks, I'll have a look.

**Comment by CyrilP** [comment]
I've just created a pre-release called v0.6-dev 
If you use HACS, you can install it if you activate beta releases.
I added new configuration parameters to configure active zones for "away" and "home" modes. There is now a "configuration" button on the integration to update them. you just have to separate them with ",", for example : 1,3,4
I'll probably add a check : if all zones are unused, I'll only enable "away" and "disabled" modes - if at least 1 zone is enabled, i'll also add "home" mode.

Can you test this version and tell me if there are problems please ?
Do you also have cameras in your system ?

**Comment by CyrilP** [comment]
@Misxs new pre-release called v0.6-dev2 because there was an error while sending commands for alarms

**Comment by Misxs** [comment]
I will try this today and let you know the result.
Thanks

**Comment by CyrilP** [comment]
Thanks. There is probably an issue with the state on the alarme panel which stays at "disarmed".  Someone has this issue with a tixal+ alarm

**Comment by Misxs** [comment]
I try your new beta version. But as you say, I cannot change the alarm from disarmed to armed. 
this is the extract of the log
2024-03-15 14:23:28.832 INFO (MainThread) [custom_components.deltadore_tydom] Incomming message - type : 2 - message : b'HTTP/1.1 200 OK\r\nServer: Tydom-001A2504DFED\r\nUri-Origin: /devices/1612289388/endpoints/1612289388/cdata\r\nContent-Type: application/json\r\nContent-Length: 0\r\nTransac-Id: 0\r\n\r\n'

**Comment by CyrilP** [comment]
I'll have a look next week

**Comment by CyrilP** [comment]
Can I have the full log with alarm state change please ?

**Comment by CyrilP** [comment]
I fixed an issue with a tyxal+ alarm log. can you check the new release v0.6-dev5  ?

**Comment by Misxs** [comment]
Hey I try and now I have the following error 
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.deltadore_tydom
Source: custom_components/deltadore_tydom/config_flow.py:160
intégration: Delta Dore TYDOM (documentation, problèmes)
S'est produit pour la première fois: 19:00:06 (1 occurrences)
Dernier enregistrement: 19:00:06

Communication error
Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 253, in async_connect
    connection = await session.ws_connect(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 832, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1147, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1180, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 221, in async_connect
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/config_flow.py", line 160, in async_step_user
    await tydom_hub.test_credentials()
  File "/config/custom_components/deltadore_tydom/hub.py", line 122, in test_credentials
    connection = await self._tydom_client.async_connect()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 266, in async_connect
    raise TydomClientApiClientCommunicationError(
custom_components.deltadore_tydom.tydom.tydom_client.TydomClientApiClientCommunicationError: Timeout error fetching information

**Comment by Misxs** [comment]
Hey Cyril

I am moving. Now the alarm is working find exept the fact that I cannot disarmed the alarm. Could you tell me the part of the log that you need to check the issue ?
Armed is working find
Disarmed is not doing any think
Thanks
Xavier

**Comment by CyrilP** [comment]
Enable debug logs on the tydom extension before arming/disarming.
Arm then disarm the alarm
Disable debug on the extension. it shoud download the needed log file

**Comment by Misxs** [comment]
Please find the log from the armed and diarmed action.
[home-assistant_deltadore_tydom_trace_log.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14704801/home-assistant_deltadore_tydom_trace_log.log)

**Comment by Misxs** [comment]
please find the  log file 
I only armed and disarmed the [alarm]
[home-assistant_deltadore_tydom_trace_log.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14704877/home-assistant_deltadore_tydom_trace_log.log)

**Comment by CyrilP** [comment]
strange, I don't see the outgoing messages to the tydom gateway in the logs... is it complete ?

**Comment by Misxs** [comment]
i think so . I will retry and send you a new log file

**Comment by Misxs** [comment]
Here is the log file.
- Armed has been done using the Alarm panel at 11:20;26 (and we can see in the log file the action)
- Disarmed has been done using the Alarm panel at 11:20:50 and we don't have any entry in the log file 
- At 11:21:22 disarmed has been done using physicaly using the Deltadore keypad and we see the result in the log.
It seem that the disarmed using the Alarm panel is not working
[home-assistant_deltadore_tydom_2024-03-22T10-21-34.497Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14721211/home-assistant_deltadore_tydom_2024-03-22T10-21-34.497Z.log)

**Comment by Misxs** [comment]
I am doing some test.
Armed the alarm whith zone is forcing the alarm to "away" whatever i choice . "HOME" or "AWAY"
after changing the message in tydom_devices 
#    await self._tydom_client.put_alarm_cdata(self._id, self._endpoint, code, "OFF", None, self.is_legacy_alarm())
        await self._tydom_client.put_alarm_cdata(self._id, self._endpoint, code, "OFF", self._tydom_client._zone_home, self.is_legacy_alarm())
the disarmed is working.

**Comment by CyrilP** [comment]
The mode is deduced from the alarmMode and alarmState parameters (see  def state(self) in ha_entities).
I expect the alarmMode to be "PART" when in HOME mode. 
Can you check theses parameters values ?

**Comment by Misxs** [comment]
I check the parameter. In fact for my CSX40 alarm the code for the zone must be "part":"1" instead of "part":"[1]". if you put in your code "part":"[1]" it will be considere has "Alway" mode. if you put "part":"1" it will considere that your arm the zone 1.
with this change, it is working. I change the code to 
- manage the night zone
- manage when it is "Alway" use only [1] "part":"[1]"
- manage when it is night with the zone_id of the night  (zone_id = 1 "part":"1")
- manage when it is Home with the zone_id of the home  (zone_id = 1 "part":"2")

Also in my case the pin_id of the alarm is not check by Tydom, whatever i enter it force the alarm. Strange no ? 
So I would be interrested to know if it is a api to check the alarm code.
Many thanks

**Comment by CyrilP** [comment]
I've just created a new beta v0.6-dev8 with the fix
