### ISSUE TITLE
Can't add integration - Unknown error

### ISSUE THREAD

**Issue by Nic062** [CyrilP/hass-deltadore-tydom-component#77]
## System Information

version | core-2024.4.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4714
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 56.5 GB
disk_used | 40.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Log Viewer (0.17.0), Duck DNS (1.17.0), AdGuard Home (5.0.7), Grafana (9.2.2), Terminal & SSH (9.13.0), Zigbee2MQTT (1.36.1-1), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), tydom2mqtt (3.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 7
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 avril 2024 à 18:32
-- | --
current_recorder_run | 27 avril 2024 à 11:33
estimated_db_size | 7393.04 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hello, 

After installing the component, I've noticed that I can't add the integration. When I enter all my information (which is valid, by the way) and validate, I get an "Unknown" error. 

For information, I used to use the tydom2mqtt module, which is now deactivated, but I'd like to use your component. 

I've checked my credentials and it's working fine.

![bug](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/6490929/88ed5148-8f6a-441f-978c-c2dd29507898)

### Reproduction steps

1. add this repository into HACS
2. download the integration from HACS
3. add new integration from setting-> device & services -> add integration and choose Delta Dore Tydom
4. data completion: user email, user password, mac address, local ip address or mediation.tydom.com address

### Debug logs

```text
Enregistreur: custom_components.deltadore_tydom
Source: custom_components/deltadore_tydom/config_flow.py:154
intégration: Delta Dore TYDOM (documentation, problèmes)
S'est produit pour la première fois: 11:36:26 (1 occurrences)
Dernier enregistrement: 11:36:26
Unknown error

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 178, in async_get_credentials
    raise TydomClientApiClientAuthenticationError(
custom_components.deltadore_tydom.tydom.tydom_client.TydomClientApiClientAuthenticationError: Tydom credentials not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/config_flow.py", line 154, in async_step_user
    user_input = await validate_input(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/config_flow.py", line 90, in validate_input
    password = await hub.Hub.get_tydom_credentials(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/hub.py", line 119, in get_tydom_credentials
    return await TydomClient.async_get_credentials(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 191, in async_get_credentials
    raise TydomClientApiClientError(
custom_components.deltadore_tydom.tydom.tydom_client.TydomClientApiClientError: Something really wrong happened!
```

**Comment by CyrilP** [comment]
Hi, 
it looks like the problem is due to the tydom gateway not having a password. 
can you please change your configuration.yaml and set the integration logs to debug and send me the logs you have when you submit the configuration form : 
```
logger:
  logs:
    custom_components.deltadore_tydom: debug
```
don't forget to hide your login and password !

**Comment by Nic062** [comment]
Thanks for your reply, I've just rebooted everything and adding the integration worked this time! Many thanks to you

**Comment by CyrilP** [comment]
Good news ! Have fun
Thanks for closing the issue

**Comment by giagara** [comment]
@CyrilP did you do some particular thing to let it work? I've got the same error and I've already restarted everything :/

**Comment by giagara** [comment]
i found my issue: i was typing the mac lowercase, but debugging the code and the api response, the mac is uppercase.
https://github.com/CyrilP/hass-deltadore-tydom-component/blob/99ed28858b907de40a852d26e0c9b57346d92d6b/custom_components/deltadore_tydom/tydom/tydom_client.py#L175C25-L175C87 here the check is done without normalizing the strings
