### ISSUE TITLE
AC Climate not show (Interface Naviclim Atlantic - 875311)

### ISSUE THREAD

**Issue by Xinnony** [CyrilP/hass-deltadore-tydom-component#83]
## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 28
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 5.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (5.6.0), Advanced SSH & Web Terminal (17.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 19
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 avril 2024 à 19:09
-- | --
current_recorder_run | 7 mai 2024 à 01:02
estimated_db_size | 91.40 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Bonjour à tous,
J'ai rajouter l'interface Naviclim Atlantic (ref:875311) qui est compatible Delta Dore Tydom (via le protocole Zigbee il me semble).
La Clim apparait et fonctionne parfaitement sur l'app Tydom, cependant, elle n'apparais pas dans HomeAssistant.
Une erreur apparait dans le debug, voir plus bas. Je pense que l'objet **aeraulic** n'a pas été implémenté par [hass-deltadore-tydom-component](https://github.com/CyrilP/hass-deltadore-tydom-component).

J'ai le même soucis pour Homebridge :
https://github.com/mgcrea/homebridge-tydom/issues/148#issue-2216442365

Merci de m'avoir lu :)

### Reproduction steps

1. Avoir l'interface Naviclim Atlantic - 875311
2. Le synchronisé avec l'app Tydom
3. Rajouté le plugin [hass-deltadore-tydom-component](https://github.com/CyrilP/hass-deltadore-tydom-component) dans Home Assistant

### Debug logs

```text
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.deltadore_tydom
Source: custom_components/deltadore_tydom/tydom/MessageHandler.py:305
intégration: Delta Dore TYDOM (documentation, problèmes)
S'est produit pour la première fois: 7 mai 2024 à 01:02:36 (291 occurrences)
Dernier enregistrement: 11:02:19

Unknown usage : aeraulic for device_id 1711649289, uid 1711649289_1711649289
```

**Comment by Xinnony** [comment]
Petit complément d'info.


<details><summary>Sur le premier screen, mon chauffage traditionnel via Tydom qui apparait sur HomeAssistant :</summary>

![IMG_5949](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/6058403/cfa4879d-6b3b-49ea-8649-892baa95d99b)

</details>

<details><summary>Sur ce screen, ma clim Atlantic qui n'apparait pas :</summary>

![IMG_5948](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/6058403/3f1a0fae-47d1-4190-a11d-ac1e989ce3b0)

</details>

**Comment by CyrilP** [comment]
Bonjour,
comme je n'ai pas cet équipement et personne ne l'avait demandé, ce n'est pas supporté.
Il me faudrait le log complet en debug de l'initialisation du plugin pour pouvoir l'implémenter

- activer le mode debug de l'integration : https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging
- redémarrer home assistant pour que les messages d'initialisation soit loggués.
- désactiver le  mode debug et télécharger le fichier de log.
- enlever les informations sensibles des messages comme email, mots de passe. éventuellement masquer l'adresse MAC en remplaçant juste les caractères. Ne pas changer la longueur du texte, j'ai un outil qui permet de rejouer les messages pour voir ce qui se passe et la modification de la taille empêche son fonctionnement

**Comment by Xinnony** [comment]
Bonjour,

Pas de soucis, le voici ci dessous :
[home-assistant_deltadore_tydom_2024-05-10T18-29-20.157Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/15278725/home-assistant_deltadore_tydom_2024-05-10T18-29-20.157Z.log)

**Comment by CyrilP** [comment]
Je viens de publier une pré-release "naviclim-v1"
Pouvez-vous faire quelques tests et me remonter les problèmes ?

**Comment by Xinnony** [comment]
> Je viens de publier une pré-release "naviclim-v1" Pouvez-vous faire quelques tests et me remonter les problèmes ?

Au début il n'apparaissait pas, après une réinstallation du plugin il apparait :)
Si je met Chauffage, Auto ou Clim, sa apparait bien dans l'app Tydom mais sur HomeAssistant sa retourne sur Eteint au bout de 2s. Je peut donc pas changer la température, il doit y avoir un retour d'information qui ne va pas.

**Comment by Xinnony** [comment]
[home-assistant_deltadore_tydom_2024-05-13T19-47-06.011Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/15299339/home-assistant_deltadore_tydom_2024-05-13T19-47-06.011Z.log)

**Comment by CyrilP** [comment]
Bonne nouvelle, il y a des trucs qui fonctionnent quand même du premier coup :)
je viens de publier "naviclim-v2", j'espère que ce sera mieux pour la remontée de l'état

**Comment by Xinnony** [comment]
Légèrement mieux, le mode clim et éteint fonctionne, le mode chauffage fait comme avant sa retourne sur le mode précédant.
Si je change le mode depuis l'apps Tydom, HomeAssistant le get bien pour le mode Clim et Eteint, par contre Chauffage toujours pas bon.

Pourtant le status est bien sur HEATING dans authorization :
![image](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/6058403/b36b0612-6075-4946-a7fd-3e903372dd2e)

Concernant le changement de température, pas de possibilité de régler la température :
![image](https://github.com/CyrilP/hass-deltadore-tydom-component/assets/6058403/20957aed-cd07-40d0-be57-f007b28acee8)

**Comment by CyrilP** [comment]
je viens de faire quelques corrections et j'ai publié une nouvelle version naviclim-v3

**Comment by Xinnony** [comment]
Chauffage, Clim, Changement de température OK ;) Un grand merci !!!

Le mode Auto par contre toujours pas bon, cependant dans TYDOM je ne vois pas comment mettre le mode AUTO, pas sur qu'on à un retour sur ce mode via Tydom (malgré que la CLIM via la télécommande puisse faire du DRY, AUTO et FAN).

**Comment by CyrilP** [comment]
finalement les modes qu'on peut activer sont : 
                  "name":"comfortMode",
                  "type":"string",
                  "permission":"w",
                  "validity":"DATA_POLLING_5MIN",
                  "enum_values":[
                     "STOP",
                     "HEATING",
                     "COOLING"
                  ]
donc on ne voit ni AUTO, ni DRY(ING), ni FAN
par contre, les modes actifs que le tydom peut remonter les mentionne bien 
                  "name":"authorization",
                  "type":"string",
                  "permission":"r",
                  "validity":"DATA_POLLING_5MIN",
                  "enum_values":[
                     "STOP",
                     "HEATING",
                     "COOLING",
                     "AUTO",
                     "VENTILATING",
                     "DRYING"
                  ]
ça viendra peut-être dans une prochaine version de firmware Tydom, c'est à surveiller

**Comment by Xinnony** [comment]
Merci pour tout ! 👍🏻
