### ISSUE TITLE
Setup without cloud credentials

### ISSUE THREAD

**Issue by myhomeiot** [CyrilP/hass-deltadore-tydom-component#88]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Old Tydom users doesn't have cloud account and access Tydom using the last 6 digits of MAC address as username and password.

### Describe the solution you'd like

Option during setup to access Tydom without cloud credentials.

### Describe alternatives you've considered

NA

### Additional context

Thanks your for your work! I was waiting for this integration a long time ;-)

Fortunately [this](https://github.com/mgcrea/homebridge-tydom) integration work well but requires extra component to be installed.

**Comment by myhomeiot** [comment]
This issue can be connected https://github.com/CyrilP/hass-deltadore-tydom-component/issues/72
BTW: Using MAC address as username and password it's also possible to connect to Tydom hub over `mediation.tydom.com` without cloud account at least it's works for Tydom 1.0.

**Comment by CyrilP** [comment]
I was thinking about refactoring the configuration dialog to support these modes.
I'll do the update as soon as I'll have more Time, probably next week

**Comment by CyrilP** [comment]
I created a new config flow, you can try it with the pre-release called "new_config_flow"
I can't test the discovery flow as I'm not home at the moment, maybe during the weekend

**Comment by myhomeiot** [comment]
@CyrilP Thanks! I test it and it's works, so I can start test other functionality!

**Comment by denics** [comment]
dear all, I have a Tydom 1 that I have bought after the electricians removed my zigbee and installed x3d wellcomm in my stores... anyway, I found this (thanks for the integration!) but I cannot find a way to set a local password and the connection via the deltadore login gives me a "unknown" answer. any idea ?
